<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
	<head>
		<title></title>
		<link rel="stylesheet" href="css/application.css" type="text/css" media="screen" title="no title" charset="utf-8">
		<meta name="viewport" content="initial-scale=1, user-scalable=no" />
	</head>
	<body>
		<div id="container">
			<div id="header">
				<ul id="nav">
					<li><a href="#search">search</a></li>
					<li><a href="#monitor">monitor</a></li>
				</ul>
			</div>
			
			<div id="contents">
				<div id="search" class="pane">
					<form id="newz_search_form">
						<div class="form_element">
							<label for="q">Keyword</label>
							<input type="text" name="Newz[q]" id="q"/>
						</div>
						
						<div class="form_element">
							<label for="Newz-area">Category</label>
							<select name="Newz[area]" id="Newz-area">
								<option label="Unknown" value="c.0">Unknown</option>
								<option label="Anime" value="c.11">Anime</option>
								<option label="Apps" value="c.1">Apps</option>
								<option label="Books" value="c.13">Books</option>
								<option label="Consoles" value="c.2">Consoles</option>
								<option label="Discussions" value="c.15">Discussions</option>
								<option label="Emulation" value="c.10">Emulation</option>
								<option label="Games" value="c.4">Games</option>
								<option label="Misc" value="c.5">Misc</option>
								<option label="Movies" value="c.6">Movies</option>
								<option label="Music" value="c.7">Music</option>
								<option label="PDA" value="c.12">PDA</option>
								<option label="Resources" value="c.14">Resources</option>
								<option label="TV" value="c.8">TV</option>
							</select>
						</div>
						<div class="submit">
							<input type="submit" name="submit" value="search"/>
						</div>
					</form>
					<ul id="results"></ul>
				</div>
				
				<div id="monitor" class="pane" style="display: none">
					<h3 class="title">Monitor</h3>
					<fieldset>
						monitor here
					</fieldset>
				</div>
				
			</div>
			<div id="footer"></div>
		</div>
		<script type="text/javascript" src="js/jquery.js"></script>
		<script type="text/javascript" src="js/application.js"></script>
	</body>
</html>